### ISSUE TITLE
reset_waiter_timeout() seems to incorrectly calculate ELB state timeout

### ISSUE THREAD

**Issue by pugsley** [awslabs/aws-codedeploy-samples#4] opened 2014-11-18 02:06 UTC
I've been having some issues with the ELB register & deregister scripts timing out too quickly and causing a failed build.

I tracked it down to my ELB HealthCheck settings:
```
Healthy Threshold: 2
Unhealthy Threshold: 5
Interval: 30 seconds
```

In `load-balancing/elb/common_functions.sh` it uses the HealthyThreshold (in `reset_waiter_timeout`) to determine when to give up waiting for the state to change before throwing a fatal error (therefore causing the deploy to fail).

IMO it should be using the `UnhealthyThreshold` so that the build fails if the instance fulfils the unhealthy threshold limits.

**Comment by suryanarayanan** [comment] 2015-02-03 19:02
Hi,
Thanks for reporting the issue. Sorry about the delayed response. We will release a fix soon.

**Comment by dlydiard** [comment] 2015-08-05 06:38
+1 the timeout calculations are broken.

My Settings (default)
# Number of times to check for a resouce to be in the desired state.
WAITER_ATTEMPTS=60

# Number of seconds to wait between attempts for resource to be in a state.
WAITER_INTERVAL=1

yet i get the following error:
[stderr]Instance is currently in state: OutOfService
[stderr]Instance failed to reach state, InService within 10 seconds

it should be 60 seconds not 10.

**Comment by alexdglover** [comment] 2015-08-26 19:56
@dlydiard Look at the reset_waiter_timeout function, it overwrites whatever initial values you set for WAITER_ATTEMPTS and WAITER_INTERVAL. That function is in turn called by wait_for_state, which is used in register-with-elb.sh and deregister-from-elb.sh after they attempt to enter/exit standby respectively.

Simple workaround for @pugsley issue - make sure your healthy threshold is equal to or greater than your unhealthy threshold.

I think the problem is that neither the healthy nor the unhealthy threshold is universally correct. It seems to me that the UnhealthyThreshold should be used when removing an instance from an ELB, and HealthyThreshold when adding the instance back.

**Comment by rpaterson** [comment] 2016-01-23 00:07
The underlying algorithm appears to be wrong.  Regardless of if I have the health check configured to 5 seconds or 5 minutes, my ELB still takes about 10 seconds to bring my app InService or take it OutOfService.

I don't think the ELB looks uses the configured health check interval when you register or deregister - apparently it just uses it on an ongoing basis after the instance is registered.

**Comment by rpaterson** [comment] 2016-01-23 00:11
The [troubleshooting guide](http://docs.aws.amazon.com/ElasticLoadBalancing/latest/DeveloperGuide/ts-elb-register-instance.html#ts-elb-register-too-long) says:
```
After the initial instance registration steps are completed (it can take up to approximately 30 seconds), the load balancer starts sending health check requests. Your instance is not InService until one health check succeeds.
```

**Comment by rpaterson** [comment] 2016-01-23 00:30
So based on that I guess we should be waiting up to `30s + health check timeout + some buffer`.

**Comment by rpaterson** [comment] 2016-01-23 00:57
Argh this doesn't take in to account connection draining either!  Really the register and deregister wait timeout algorithms are totally different:

Deregister: `30 + connection-draining-timeout`
Register: `30 + health-check-timeout`

**Comment by rpaterson** [comment] 2016-02-12 16:07
Fixed by PR 39.  Thanks for merging @Jmcfar!

**Closed** 2016-07-05 18:46 UTC
